{ ... }:
{
  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = false;
      upgrade = true;
      cleanup = "zap"; # Uninstall all programs not declared
    };
    global = {
      brewfile = true;
      autoUpdate = true;
    };
    # Add taps (repositories)
    taps = [
      "houmain/tap"
      "acarl005/formulas"
      "domt4/autoupdate"
      "felixkratz/formulae"
      "lzt1008/powerflow"
      "jesseduffield/lazygit"
      "jstkdng/programs"
      "nikitabobko/tap"
      # "crystal-ameba/ameba"
    ];
    # Add brews (packages)
    brews = [
      {
        name = "sketchybar";
        start_service = false;
      }
      "ccusage"
      "mole"
      # "rclone"
      "dfu-util"
      "wtfutil"
      "carapace"
      # "music-decoy"
      "gawk"
      "gnu-tar"
      "findutils"
      "gnu-getopt"
      "gnu-sed"
      "coreutils"
      "diffutils"
      "gpatch"
      "grep"
      "quilt"
      "apr"
      "apr-util"
      "swig"
      "subversion"
      "rustup"
      "codecrafters-io/tap/codecrafters"
      "exercism"
      # "whisper-cpp"
      "sox"
      "deno"
      "mise"
      "swiftlint"
      "bat"
      # "tailscale"
      "nvm"
      "podman"
      "podman-compose"
      "bgrep"
      # "broot"
      "gnu-sed"
      # "btop"
      "chezmoi"
      "hidapi"
      "make"
      "cmake"
      "coreutils"
      "curl"
      # "direnv"
      "djvu2pdf"
      "djvulibre"
      "e2fsprogs"
      "entr"
      "exiftool"
      # "eza"
      "fastfetch"
      "fd"
      "ffmpeg"
      "ffmpegthumbnailer"
      "fftw"
      # "fish"
      "flac"
      "fmt"
      "fontconfig"
      "fontforge"
      "forgit"
      "freetype"
      # "fzf"
      "fzy"
      "gcc"
      "gh"
      "git"
      "git-cal"
      "git-delta"
      "git-extras"
      "git-hooks-go"
      "git-imerge"
      "git-now"
      "git-recent"
      "git-when-merged"
      "glow"
      "gnutls"
      "go"
      "gperf"
      "graphicsmagick"
      "graphviz"
      "hadolint"
      "highlight"
      "howdoi"
      "htop"
      "hyperfine"
      "imagemagick"
      "iperf3"
      "jq"
      "kanata"
      "lame"
      "lazygit"
      "lf"
      "libexif"
      "llvm"
      "lpeg"
      "ls-go"
      "lsd"
      "lua"
      "lua-language-server"
      "luajit"
      "luarocks"
      "lynx"
      "lzo"
      "mas"
      "marksman"
      "miller"
      "mozjpeg"
      "mpg123"
      "mpv"
      "mujs"
      "mupdf"
      "ncdu"
      "neovim"
      "netcat"
      "netpbm"
      "ninja"
      "nlohmann-json"
      "ouch"
      "p7zip"
      "pandoc"
      "pango"
      "pdftoipe"
      "pillow"
      "pinentry"
      "pinentry-mac"
      "pixman"
      "pkgconf"
      "plantuml"
      "poppler"
      "prettier"
      "procs"
      "pymupdf"
      "pyright"
      "python-lsp-server"
      "python-setuptools"
      # "pyenv"
      # "ranger"
      "ripgrep"
      "ripgrep-all"
      "rsync"
      # "ruff"
      "rust"
      "sevenzip"
      "shared-mime-info"
      "smartmontools"
      "snappy"
      "socat"
      "starship"
      "stylua"
      "terminal-notifier"
      "tlrc"
      "tmux"
      "tokei"
      "tree"
      "tree-sitter"
      "uchardet"
      # "ueberzugpp"
      "unar"
      "uv"
      # "vercel-cli"
      "viu"
      "watch"
      "websocat"
      "wget"
      "yarn"
      # "yazi"
      "yq"
      # "zellij"
      # "zoxide"
      # "zsh"
      "zsh-autocomplete"
      # "zsh-history-substring-search"
      "zsh-syntax-highlighting"

      # other
      "chafa"
      "libsixel"
      "spdlog"
      "tbb"
      "cfitsio"
      "cgif"
      "libaec"
      "hdf5"
      "libmatio"
      "libspng"
      "uthash"
      "libdicom"
      "libxml2"
      "openslide"
      "vips"
      # "ice"
      "helix"
      "ruby"
      "cocoapods"

      # ─── added by add_tools.sh ───
      "xh"               # HTTPie на Rust, ~10× быстрее, тот же синтаксис
      "doggo"            # современный dig: цветной, JSON, DoH/DoT/DoQ
      "gron"             # JSON → greppable строки: `cat x.json | gron | grep …`
      "dasel"            # селектор JSON/YAML/TOML/XML/CSV единым синтаксисом
      "just"             # запускалка project-команд, лучше Make
      "navi"             # interactive cheatsheets (Ctrl-G), shell-friendly
      "lnav"             # лог-навигатор с SQL-фильтром и парсингами форматов
      "dust"             # `du` с барами и UTF-8 деревом
      "bottom"           # `btm` — современный TUI-монитор, UX лучше btop на macOS
      "bandwhich"        # network usage per-process (нужен sudo)
      "pueue"            # очередь долгих команд (docker build, pip, ffmpeg)
      "glab"             # GitLab CLI (для EPAM GitLab)
      "act"              # запуск GitHub Actions локально через Docker/podman

    ];
    # Add casks (macOS applications)
    casks = [
      "macfuse"
      "libreoffice"
      "keycastr"
      # "remnote"
      "tidal"
      "supasidebar"
      "claude"
      "antinote"
      "processspy"
      # "multitouch"
      "lasso-app"
      # "paste"
      "soundsource"
      "rectangle-pro"
      # "rescuetime"
      "applite"
      "adguard"
      # "superwhisper"
      "qutebrowser"
      "codex"
      # "kando"
      # "hyperkey"
      # "command-x"
      "orbstack"
      # "capacities"
      # "todoist-app"
      "zen"
      "mouseless"
      # "folder-preview-pro"

      "istat-menus"
      "reader"
      "bleunlock"
      "istherenet"
      # "mindmac"
      "powerflow"
      # "dockdoor"
      "betterdisplay"
      # "slidepad"
      "coconutbattery"
      # "lunar"
      "homerow"
      "launchcontrol"
      "qbserve"
      "pearcleaner"
      # "hammerspoon"
      "betterzip"
      "arq"
      # "shottr"
      "zed"
      # "marvin"
      "anki"
      # "voiceink"
      "leader-key"
      "script-debugger"
      "dropbox"
      # "keysmith"
      # "default-folder-x"
      # "downie"
      "forklift"
      "anytype"
      "reverso"
      "cleanshot"
      # "pixelsnap"
      "ghostty"
      "kindavim"
      "keyboard-maestro"
      # "dropbox-dash"
      "proton-mail"
      "proton-mail-bridge"
      "protonvpn"
      "proton-pass"
      # "proton-drive"
      # "backblaze"
      "vivaldi"
      "airbuddy"
      "bettertouchtool"
      "bartender"
      "cleanmymac"
      "clop"
      "dash"
      # "hazeover"
      "popclip"
      # "deepl"
      "devutils"
      "orion"
      # "neohtop"
      "telegram"
      "podman-desktop"
      "lm-studio"
      # "oracle-jdk"
      "ollama-app"
      "balenaetcher"
      "fsmonitor"
      "folx"
      "istat-menus"
      # "busycal"
      # "busycontacts"
      # "calibre"
      "dbeaver-community"
      "cursor"
      "figma"
      "karabiner-elements"
      # "raycast"
      # "font-hack-nerd-font"
      # "font-jetbrains-mono-nerd-font"
      # "font-symbols-only-nerd-font"
      "git-credential-manager"
      "google-chrome"
      "iina"
      "iterm2"
      "itermai"
      "macpilot"
      "mediainfo"
      # "monitorcontrol"
      "mos"
      # "notion"
      # "obsidian"
      "postman"
      "qlmarkdown"
      "send-to-kindle"
      "sf-symbols"
      "sublime-text"
      "syntax-highlight"
      "visual-studio-code"
      "warp"
      "wezterm"
      "zoom"

      # ─── added by add_tools.sh ───
      "blockblock"       # Objective-See: monitor persistence (LaunchAgents/Daemons)
      "knockknock"       # Objective-See: однократный аудит persistently-установленного
    ];
  };
}
