{ ... }: {
  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = false;
      upgrade = true;
      cleanup = "zap"; # Uninstall all programs not declared
    };
    global = {
      brewfile = true;
      lockfiles = true;
      autoUpdate = true;
    };
    # Add taps (repositories)
    taps = [
      "houmain/tap"
      "acarl005/formulas"
      "domt4/autoupdate"
      "felixkratz/formulae"
      "lzt1008/powerflow"
      "homebrew/command-not-found"
      "jesseduffield/lazygit"
      "jstkdng/programs"
      "nikitabobko/tap"
      # "crystal-ameba/ameba"
    ];
    # Add brews (packages)
    brews = [
      {
        name = "sketchybar";
        start_service = false;
      }
      "duckduckgo"
      "dfu-util"
      "wtfutil"
      "carapace"
      # "music-decoy"
      "gawk"
      "gnu-tar"
      "findutils"
      "gnu-getopt"
      "gnu-sed"
      "coreutils"
      "diffutils"
      "gpatch"
      "grep"
      "quilt"
      "apr"
      "apr-util"
      "swig"
      "subversion"
      "rustup"
      "codecrafters-io/tap/codecrafters"
      "exercism"
      "whisper-cpp"
      "sox"
      "deno"
      "mise"
      "swiftlint"
      "bat"
      # "tailscale"
      "nvm"
      "podman"
      "podman-compose"
      "bgrep"
      # "broot"
      "gnu-sed"
      # "btop"
      "chezmoi"
      "hidapi"
      "make"
      "cmake"
      "coreutils"
      "curl"
      # "direnv"
      "djvu2pdf"
      "djvulibre"
      "e2fsprogs"
      "entr"
      "exiftool"
      # "eza"
      "fastfetch"
      "fd"
      "ffmpeg"
      "ffmpegthumbnailer"
      "fftw"
      # "fish"
      "flac"
      "fmt"
      "fontconfig"
      "fontforge"
      "forgit"
      "freetype"
      # "fzf"
      "fzy"
      "gcc"
      "gh"
      "git"
      "git-cal"
      "git-delta"
      "git-extras"
      "git-hooks-go"
      "git-imerge"
      "git-now"
      "git-recent"
      "git-when-merged"
      "glow"
      "gnutls"
      "go"
      "gperf"
      "graphicsmagick"
      "graphviz"
      "hadolint"
      "highlight"
      "howdoi"
      "htop"
      "hyperfine"
      "imagemagick"
      "iperf3"
      "jq"
      # "kanata"
      "lame"
      "lazygit"
      "lf"
      "libexif"
      "llvm"
      "lpeg"
      "ls-go"
      "lsd"
      "lua"
      "lua-language-server"
      "luajit"
      "luarocks"
      "lynx"
      "lzo"
      "mas"
      "marksman"
      "miller"
      "mozjpeg"
      "mpg123"
      "mpv"
      "mujs"
      "mupdf"
      "ncdu"
      "neovim"
      "netcat"
      "netpbm"
      "ninja"
      "nlohmann-json"
      "node@22"
      "node-build"
      "nodenv"
      "ouch"
      "p7zip"
      "pandoc"
      "pango"
      "pdftoipe"
      "pillow"
      "pinentry"
      "pinentry-mac"
      "pixman"
      "pkgconf"
      "plantuml"
      "poppler"
      "prettier"
      "procs"
      "pymupdf"
      "pyright"
      "python-lsp-server"
      "python-setuptools"
      # "pyenv"
      # "ranger"
      "ripgrep"
      "ripgrep-all"
      "rsync"
      # "ruff"
      "ruff-lsp"
      "rust"
      "sevenzip"
      "shared-mime-info"
      "smartmontools"
      "snappy"
      "socat"
      "starship"
      "stylua"
      "terminal-notifier"
      "tlrc"
      "tmux"
      "tokei"
      "tree"
      "tree-sitter"
      "uchardet"
      # "ueberzugpp"
      "unar"
      "uv"
      # "vercel-cli"
      "viu"
      "watch"
      "websocat"
      "wget"
      "yarn"
      # "yazi"
      "yq"
      # "zellij"
      # "zoxide"
      # "zsh"
      "zsh-autocomplete"
      # "zsh-history-substring-search"
      "zsh-syntax-highlighting"

      # other
      "chafa"
      "libsixel"
      "spdlog"
      "tbb"
      "cfitsio"
      "cgif"
      "libaec"
      "hdf5"
      "libmatio"
      "libspng"
      "uthash"
      "libdicom"
      "libxml2"
      "openslide"
      "vips"
      # "ice"
      "helix"
    ];
    # Add casks (macOS applications)
    casks = [
      "soundsource"
      "rize"
      "rectangle-pro"
      "rescuetime"
      "applite"
      "alfred"
      "adguard"
      "superwhisper"
      "qutebrowser"
      "codex"
      "min"
      # "kando"
      # "hyperkey"
      # "command-x"
      "simsim"
      "mist"
      "orbstack"
      # "capacities"
      # "todoist-app"
      "zen"
      "mouseless"
      # "folder-preview-pro"

      "spotify"
      "istat-menus"
      "reader"
      "bleunlock"
      "obs"
      "istherenet"
      # "mindmac"
      "raindropio"
      "powerflow"
      # "dockdoor"
      "betterdisplay"
      # "slidepad"
      "coconutbattery"
      # "lunar"
      "homerow"
      "launchcontrol"
      # "qbserve"
      "pearcleaner"
      # "hammerspoon"
      "betterzip"
      "arq"
      # "shottr"
      "zed"
      # "marvin"
      "anki"
      "voiceink"
      "leader-key"
      "script-debugger"
      "dropbox"
      # "keysmith"
      # "default-folder-x"
      # "downie"
      "forklift"
      "marked-app"
      "anytype"
      "reverso"
      "cleanshot"
      "pixelsnap"
      "ghostty"
      "kindavim"
      "keyboard-maestro"
      # "dropbox-dash"
      "proton-mail"
      "proton-mail-bridge"
      "protonvpn"
      "proton-pass"
      "bluetility"
      # "proton-drive"
      # "backblaze"
      "vivaldi"
      "airbuddy"
      "aldente"
      "bettertouchtool"
      "bartender"
      "cleanmymac"
      "clop"
      "dash"
      # "hazeover"
      "popclip"
      # "deepl"
      "devutils"
      "orion"
      # "neohtop"
      "telegram"
      "podman-desktop"
      "lm-studio"
      # "oracle-jdk"
      "ollama-app"
      "ollamac"
      "balenaetcher"
      "fsmonitor"
      "folx"
      "istat-menus"
      # "busycal"
      # "busycontacts"
      # "calibre"
      "dbeaver-community"
      "cursor"
      "figma"
      "karabiner-elements"
      "raycast"
      # "font-hack-nerd-font"
      # "font-jetbrains-mono-nerd-font"
      # "font-symbols-only-nerd-font"
      "fontforge-app"
      "git-credential-manager"
      "google-chrome"
      "iina"
      "iterm2"
      "itermai"
      "macpilot"
      "mediainfo"
      # "monitorcontrol"
      "mos"
      # "notion"
      # "obsidian"
      "postman"
      "qlcolorcode"
      "qlmarkdown"
      "qlstephen"
      "quicklook-json"
      "quicklookase"
      "send-to-kindle"
      "sf-symbols"
      "sublime-text"
      "syntax-highlight"
      "visual-studio-code"
      "warp"
      "zoom"
    ];
  };
}
